[package]
name = "mu2-tweaks"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xplm = { git = "https://github.com/samcrow/rust-xplm.git", version = "0.3.1" }

[lib]
name = "win"
crate-type = ["cdylib"]
bench = false