[package]
name = "mu2-tweaks"
version = "0.1.3"
edition = "2021"

[dependencies]
xplm = { git = "https://github.com/JDeeth/rust-xplm.git", branch = "main" }

[lib]
name = "win"
crate-type = ["cdylib"]
bench = false